FROM alpine:3.15 AS certs
RUN apk add --no-cache ca-certificates && update-ca-certificates
RUN adduser -D -g '' appuser

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=certs /etc/passwd /etc/passwd
USER appuser
ENTRYPOINT ["/bin/layout"]
ADD layout /bin/